# Generated by Django 4.1.2 on 2022-10-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('blog_date', models.DateField()),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI')], max_length=20)),
            ],
        ),
    ]
