# Generated by Django 5.0.7 on 2024-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
