# Generated by Django 4.1.5 on 2023-01-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
            ],
        ),
    ]
