# Generated by Django 4.1.5 on 2023-02-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(auto_now=True),
        ),
    ]
