# Generated by Django 4.1.2 on 2022-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('subject', models.CharField(choices=[('English', 'ENGLISH'), ('hindi', 'HINDI')], max_length=50)),
            ],
        ),
    ]
