# Generated by Django 5.0.7 on 2024-08-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogData',
            new_name='Blog_data',
        ),
    ]
