# Generated by Django 5.0.7 on 2024-08-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_blogdata_blog_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_data',
        ),
    ]
