# Generated by Django 4.1.5 on 2023-01-31 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_blog', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writer_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
