# Generated by Django 4.1.5 on 2023-02-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_blog', '0004_remove_blog_writer_name_blog_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
