# Generated by Django 4.1.3 on 2022-11-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_time', '0002_alter_service_service_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon_time.salon'),
            preserve_default=False,
        ),
    ]
