# Generated by Django 4.1.3 on 2022-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_time', '0003_bookings_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
