# Generated by Django 4.1.2 on 2022-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('language', models.CharField(choices=[('hindi', 'HINDI'), ('english', 'ENGLISH')], max_length=20)),
            ],
        ),
    ]
