# Generated by Django 4.1.2 on 2022-10-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
